- components/MarkdownEditor/index.js
> fix editor bg

- pages/api/upload/post.js
> Direct slack link to post page

- components/MarkdownEditor/index.js
> Link user in new editor

- authentication/components/Email.js
- authentication/components/Google.js
- authentication/components/NoAuthEmail.js
- authentication/components/index.js
- pages/api/auth/[...nextauth].js
- pages/login/index.js
> Improve layout for email auth alongwith oauth providers

- README.md
> Add Vercel deploy button

- components/Button/index.js
- components/MarkdownEditor/index.js
- components/NamePlate/CommenterNamePlate.js
- package-lock.json
- package.json
- pageUtils/post/styles.js
- pages/post/[id].js
* Editing and replying to comments has been temporarily disabled
* Use react-markdown for rendering comments
* Update how comments are rendered
> Comment styling and (temp) disable multi-level commenting

- components/TopBar/index.js
> Fix breadcrumb font size on mobile

- components/DropdownMenu/index.js
> Remove last-child bottom border

- pageUtils/post/styles.js
> Increase comment text font size

- components/Button/index.js
- components/PostList/index.js
- components/TopBar/index.js
- pageUtils/post/styles.js
- pages/new/index.js
- pages/post/[id].js
- pages/theme.css
- utils/dateTime/index.js
> Style tweaks

- pageUtils/post/styles.js
- pages/post/[id].js
> Fix comment box alignment

- components/UserSettings/index.js
> Theme toggler hover style updates/fixes

- components/Button/index.js
> .primary.with-shortcut hover state fix

- components/NamePlate/CommenterNamePlate.js
> Capitalize date on comments

- pageUtils/post/styles.js
- pages/post/[id].js
> Update post edit button layout

- pages/login/index.js
> Update login screen mobile mode

- components/Button/index.js
- components/Notifications/index.js
> Use filled icon when notifications are present

- authentication/components/GitHub.js
- authentication/components/index.js
- pages/api/auth/[...nextauth].js
- pages/login/index.js
> Label first oauth provider button in oauth list

- components/PostList/index.js
- pages/theme.css
> Add hover layer shadow for light mode

- pages/api/get-notifications.js
> Dont show notifications for user's own actions

- components/TopBar/index.js
- next.config.js
- package-lock.json
- package.json
- pages/index.js
- public/icons/hashtag.svg
* Use next-svgr
* Download hashtag icon from remixicons
* Minor svg fix
> Manual hashtag icon addn and fix hashtag filtering

- components/DropdownMenu/index.js
- components/Notifications/index.js
- components/TopBar/index.js
- components/UserSettings/index.js
* Encapsulate user settings dropdown component and its corresponding trigger
* Remove dropdownmenu.content overrides
* Simplify controls and components for dropdown menu
> Dropdown cleanup

- pages/new/index.js
> Restrict newline + fix bckspace multiline behavior in title and subtitle input fields

- components/CreateOrg/index.js
- components/Input/index.js
- pageUtils/post/styles.js
- pages/api/create-post.js
- pages/api/create-user.js
- pages/post/[id].js
- pages/theme.css
- state/user/index.js
> Provide error message when username already exists

- components/TopBar/index.js
> Update width constrain of topbar

- components/CommentBox.js
- pageUtils/post/styles.js
> Translucent hovering comment box

- pageUtils/post/styles.js
> Update comment left border

- pageUtils/post/styles.js
> Remove shadow and add border to post content box

- pageUtils/post/styles.js
> Add top border to content inside post box

- pages/new/index.js
> Update input fields border color on new page

- authentication/components/Email.js
- components/Button/index.js
> Update default button state style

- components/Button/index.js
- components/Notifications/index.js
- components/PostList/index.js
- components/TopBar/index.js
- components/UserSettings/index.js
> Restyle navbar

- package-lock.json
- package.json
- pages/api/_utils/slack-notifications.js
- pages/api/create-post.js
- pages/new/index.js
- utils/dateTime/index.js
* to #general in production
* to #flux-sandbox in development
> Slack notifications
